services:
  api.controller.videos.getVideos:
    class: VideoLibrary\Api\Infrastructure\Ui\Http\Controller\Videos\GetVideosController
    arguments:
      - '@api.query.video.getVideosHandler'
    public: true

  api.controller.videos.createVideo:
    class: VideoLibrary\Api\Infrastructure\Ui\Http\Controller\Videos\CreateVideoController
    arguments:
      - '@api.command.video.createVideoHandler'
    public: true
